version: '3.8'

services:
  postgres-db:
    image: postgres
    container_name: meetups-postgres-db
    environment:
      POSTGRES_USER: postgres      # Set the database username
      POSTGRES_PASSWORD: postgres  # Set the database password
      POSTGRES_DB: meetups  # Set the default database name
    ports:
      - "5435:5432"             # Expose the PostgreSQL port
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist database data locally
    restart: always             # Automatically restart if the container stops

volumes:
  postgres-data:
    driver: local
